### ISSUE TITLE
This is great! Can I contribute?

### ISSUE THREAD

**Issue by facontidavide** [mikeferguson/ros2_cookbook#1]
Hi,

I found this very useful and a nice complement to the **ros2/demo** repository.

Would you accept external contributions?
I would like to add a page about "inter-process communication" and another about "lifecycle nodes".

**Comment by mikeferguson** [comment]
Absolutely open to external contributions - open a PR with any ideas!

Both inter-process comms and lifecycle nodes would be great topics to cover - I actually don't feel that I know them well enough yet to write about, so those would be awesome contributions.
