### ISSUE TITLE
Inline LaTeX rendering

### ISSUE THREAD

**Issue by jkaniuka** [mikeferguson/ros2_cookbook#16]
Hi @mikeferguson, you did a great job with this cookbook :clap:. However, I noticed that inline LaTeX expressions do not render properly (e.g., the powers in the QoS chapter). I think you should add MathJax to `mkdocs.yml` file as described [here](https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-docsjavascriptsmathjaxjs) :wink:

**Comment by mikeferguson** [comment]
Thanks for the pointer: https://github.com/mikeferguson/ros2_cookbook/commit/df27cb8e15221aceba29888320979f8a44d81598
