### ISSUE TITLE
ament_cmake guide out of date

### ISSUE THREAD

**Issue by Ryanf55** [mikeferguson/ros2_cookbook#20]
Hey there,

Just FYI your cookbook entry for ament_cmake is out of date. You might just want to deprecate it and refer to the upstream tutorial because that's up to date. 

https://docs.ros.org/en/humble/How-To-Guides/Ament-CMake-Documentation.html

**Comment by mikeferguson** [comment]
7f59b70174cb72c4a6a7a51ad4f046f859f8c6dc
